version: "3"
services:
  app:
    container_name: app
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '8910:80'
    expose:
      - '8910'
    environment:
      - API_URL=url