<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="refresh" content="45">
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <h1>Price of Bitcoin right now:</h1>
    <br />

    <?php echo "$ ".$prices['USD']. " / " . $prices['EUR'] . " €"; ?>

    <br />
    <br />

    <p>The application refreshes after 45s to show correct data.</p>
</div>
</body>
</html>




